### ISSUE TITLE
Programme drucken Button erscheint nicht

### ISSUE THREAD

**Issue by dirkbe** [homematic-community/hm-print#11]
Hallo,

nach der Installation von hm-print 2.3 erscheint unter Startseite > Programme und Verknüpfungen > Programme keine Schaltfläche für Programme drucken. Auch unter den einzelnen Programmen befindet sich kein Button zum drucken.

Umgebung: RaspberryMatic 3.53.30.20201024
Addons: Email 1.7.1, Cuxd 2.4.4, Philips Hue 3.1.0
Browser: Chrome 87.0.4280.88 (Official Build) (x86_64), Safari 14.0.1 (15610.2.11.51.10, 15610)

Im Log sind keine Fehler enthalten.

**Comment by jp112sdl** [comment]
BrowserCache mal gelöscht?

**Comment by dirkbe** [comment]
Ja, das wars! Danke!
Da hab ich extra 2 Browser ausprobiert aber daran hab ich nicht gedacht...
