### ISSUE TITLE
HM-Print (2.3) CCU2 FW: 2.55.5 -Problem

### ISSUE THREAD

**Issue by rhiermei** [homematic-community/hm-print#12]
Auf der CCU2 mit der Firmware 2.55.5 wurde HM-Print Version 2.3 installiert.
Im Gegensatz zu früher taucht die Option Programme drucken unter 
Programme und Zentralverknüpfungen / Programm bearbeiten
nicht mehr auf.
Habe ich eine Möglichkeit dies zu ändern?
Vieln Dank schon mal für die Antwort.
Grüße - Reiner

**Comment by jp112sdl** [comment]
Hi

> Im Gegensatz zu früher taucht die Option Programme drucken unter

Hast du die alte Version vorher **deinstalliert**?

**Comment by rhiermei** [comment]
Vielen Dank für den schnellen Tipp.
Ich habe die installierte Version deinstalliert und die aktuelle noch einmal installiert.
Jetzt ist wieder alles wie gewohnt.
Viele Grüße aus Ulm - Reiner
