### ISSUE TITLE
Button disappeared in CCU3 firmware 3.53.26

### ISSUE THREAD

**Issue by michaelotto** [homematic-community/hm-print#5]
The Button "Programme drucken" has disappeared in CCU3 firmware 3.53.26, even though the addon is still installed. Downgrading the firmware makes the button appear again, so it is clearly a firmware compatibility issue.

**Comment by jp112sdl** [comment]
This project seems to be no longer active.
I've forked the repository and modified the files to be compatible with 3.53.26.
Please have a look at https://github.com/jp112sdl/hm-print/releases

**Comment by Thomas267** [comment]
Hi, i have the same issue after installing 3.53.30 on RaspberryMatic. Even after the installation of hm-print-2.1.tar.gz the button is not visible.

**Comment by jp112sdl** [comment]
> Even after the installation of hm-print-2.1.tar.gz the button is not visible.

Did you uninstall the previous version of hm-print before installing version 2.1 ?
https://homematic-forum.de/forum/viewtopic.php?f=41&t=19296&start=210#p599840

**Comment by Thomas267** [comment]
Ups. I missed this. I have now
* deinstalled hm-print 2.1
* restarted RaspberryMatic
* installed hm-print 2.1 again
and it is working! Many thanks for your hint

**Comment by jens-maus** [comment]
@jp112sdl Übrigens, wann schickst du ein PullRequest bzgl. deiner Änderungen an hm-print? Sicherlich nicht sehr günstig wenn es jetzt auf dauer zwei repos geben soll. @litti könnte ja auch drüber nachdenken das Projekt der homematic-community (https://github.com/homematic-community) zu vermachen, dann könnte das dort weiterentwickelt werden (meine Addons werde ich bald da auch noch reinschieben). Und eigentlich stand auch mal auf dem Plan das gesamte hm-print komplett als WebUI Patch in RaspberryMatic direkt zu integrieren. Aber nur soviel nebenbei.

**Comment by jp112sdl** [comment]
> Übrigens, wann schickst du ein PullRequest bzgl. deiner Änderungen an hm-print?

Das wäre mit ein paar Klicks getan, aber da sich die ganze Zeit über weder HMSide noch litti zu Wort gemeldet haben (und auch auf das Issue #4 von psytester 1 Jahr lang niemand reagiert hat), halte ich das Projekt hier an der Stelle für _"aufgegeben"_.

Ich lasse mich da gern einer anderen Meinung überzeugen, sofern sich der Maintainer dieses Projekts zu Wort meldet.

**Comment by litti** [comment]
Ich kann gerne PRs mergen, habe momentan allerdings keinen Antrieb, das Projekt über meinen eigenen Nutzen hinweg weiterzuentwickeln (und ich habe es nie genutzt ;-))

**Comment by jens-maus** [comment]
@litti Super, könntest du das Projekt dann nicht einfach gleich einfach der "homematic-community" github organisation (https://github.com/homematic-community) übereignen, dann kann da von mehreren Seite aus ggf. dran weiterentwickelt werden.

**Comment by litti** [comment]
Klar, wenn da in der Community etwas leben reinkommt, mache ich das gerne - momentan ist es da ja auch ziemlich tot...

**Comment by jens-maus** [comment]
@litti Na das ist ja das Henne/Ei problem. Wie gesagt, ich werde in nöchster Zeit auch einige meiner Addons der Community übereignen sodass da im Zweifel alle in der Gruppe auch Dinge direkt anpassen können. Und wenn du das jetzt auch mit hm-print machst kann @jp112sdl ja gleich seine Anpassungen für die 3.53 da einchecken und releasen... Wäre toll!

**Comment by jp112sdl** [comment]
> momentan ist es da ja auch ziemlich tot...

Ja es ist ziemlich ruhig geworden um die _üblichen Verdächtigen_.

> kann @jp112sdl ja gleich seine Anpassungen für die 3.53 da einchecken und releasen

Die Frage ist, wie wir Differenzen handhaben. 
Es geht um das `generate_img.sh` - das habe ich an meine Umgebung angepasst.
https://github.com/litti/hm-print/compare/master...jp112sdl:master#diff-67aac38c10ca7df6cc715b00876041ee

Desweiteren muss dann die `update-check.cgi` noch auf den neuen Link angepasst werden.
https://github.com/litti/hm-print/compare/master...jp112sdl:master#diff-7e14f28e3d3965b87cb4f0ab8db0ce80

**Comment by jp112sdl** [comment]
> momentan ist es da ja auch ziemlich tot...

Ja es ist ziemlich ruhig geworden um die _üblichen Verdächtigen_.


Die Frage ist, wie wir Differenzen handhaben. 
Speziell das `generate_img.sh` - das habe ich an meine Umgebung angepasst.
https://github.com/litti/hm-print/compare/master...jp112sdl:master#diff-67aac38c10ca7df6cc715b00876041ee

Desweiteren muss dann die `update-check.cgi` noch auf den neuen Link angepasst werden.
https://github.com/litti/hm-print/compare/master...jp112sdl:master#diff-7e14f28e3d3965b87cb4f0ab8db0ce80

**Comment by jens-maus** [comment]
So, inzwischen habe ich den PR von @jp112sdl integriert und auch einen neuen 2.2 release rausgebracht. Besser wäre es aber in der Tat wenn @litti das Projekt hier bitte an die homematic-community gruppe übertragen könnte, dann könnte in zukunft @jp112sdl oder meine wenigkeit oder eben andere daran änderungen direkt vornehmen und dann passiert es hoffentlich nicht nochmal das so ein fork + separatem release notwendig ist weil gedacht wird das dieses repo hier obsolete/tot ist.

**Comment by litti** [comment]
Ich habe das Projekt übertragen.

**Comment by jens-maus** [comment]
@litti Danke! Das ist ein Schritt in die richtige Richtung. Kannst du aber bitte noch das Repo dem @homematic-community/ccu-addon-devs Team zuordnen? Momentan hast du das dem allgemeinen Team zugeordnet, es erscheint mir allerdings besser in diesem Team aufgehoben. Danke.

**Comment by litti** [comment]
Ja, ist schon erledigt.
