### ISSUE TITLE
Referenz in update-check.cgi auf Repository

### ISSUE THREAD

**Issue by ptweety** [homematic-community/hm-print#7]
https://github.com/homematic-community/hm-print/blob/8625e5f3bb38e18a639146e7c3d48eca61bf36b0/www/update-check.cgi#L3-L4

Müsste das nicht auf `homematic-community` geändert werden?

**Comment by jens-maus** [comment]
Ja, mit der nächsten release version. Allerdings mat github automatisch bis dahin ein url redirect. Also nicht sehr kritisch.

**Comment by jens-maus** [comment]
Done, siehe #8
